# Generated by Django 3.2.10 on 2021-12-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_role', models.BooleanField(default=False)),
            ],
        ),
    ]
