# Generated by Django 3.2.10 on 2021-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membermanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='admin_role',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Regular Member', 'Regular Member')], default='Regular Member', max_length=50, null=True),
        ),
    ]
